services:
  php:
    build: ./php
    container_name: php
    volumes:
      - ./php/www/:/var/www/html
    privileged: true
    ports:
      - ${PHP_PORT}:80
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EXPRESS_URL=${EXPRESS_URL}
  express:
    container_name: express
    build: ./express
    volumes: 
      - ./express:/app
      - ./express/node_modules:/app/node_modules
    tty: true
    ports:
      - "${EXPRESS_PORT}:3000"
    environment:
      - CORS_URL=${CORS_URL}
  db:
    container_name: db
    image: postgres:13
    ports:
      - 54320:5432
    volumes:
      - ${INITDB_VOLUME:-./initdb.d:/docker-entrypoint-initdb.d}
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    deploy:
      replicas: ${DB_REPLICAS:-1}
volumes:
  node_modules: {}
