name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          cat << EOF > .env
          DATABASE_URL=postgresql://johndoe:postgres@db:5432/mydb
          PHP_PORT=80
          EXPRESS_PORT=3000
          EXPRESS_URL=http://localhost:3000
          CORS_URL=http://localhost
          DB_REPLICAS=1
          EOF
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build containers
        run: docker compose build
      
      - name: Install Express dependencies
        run: docker compose run --rm express npm i
      
      - name: Start containers
        run: docker compose up -d
      
      # DBの準備完了を待つ
      - name: Wait for database
        run: |
          timeout 30 bash -c 'until docker compose exec -T db pg_isready -h localhost -U johndoe -d mydb -p 5432; do sleep 1; done'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: playwright/package-lock.json
      
      - name: Install Playwright dependencies
        working-directory: playwright
        run: |
          npm i
          npm run test:install
      
      - name: Wait for services to be ready
        run: |
          # PHPサーバーが立ち上がるまで待機
          timeout 30 bash -c 'while ! curl -s http://localhost:80 > /dev/null; do sleep 1; done'
          # 少し待機して各サービスの準備完了を確実に
          sleep 5
      
      - name: Run Playwright tests
        working-directory: playwright
        run: npm run test
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
      
      - name: Stop containers
        if: always()
        run: docker compose down 